//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int CustomerID { get; set; }
        public int OrderID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<System.DateTime> FilledDate { get; set; }
        public string Status { get; set; }
        public int Amount { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
